# web server
nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    # app
    - ./app/site_php:/usr/share/nginx/html
    # nginx configs
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    # certificates
    - ./nginx/ca/server.crt/:/etc/nginx/server.crt:ro
    - ./nginx/ca/server.key/:/etc/nginx/server.key:ro
  links:
    - fpm56:host_php56
    - tomcat:host_tomcat
    - fpm56:host_php
    - mysql:host_mysql


tomcat:
  image: tomcat:7.0.77-jre8
  ports: 
    - "8080"
  volumes:
    - ./app/site_tomcat:/usr/local/tomcat/webapps/website
  links:
    - mysql:host_mysql

# php-fpm
fpm56:
  build: ./php5.6-fpm
  #entrypoint: echo "ijustbedisabled"
  #entrypoint: tail -f /var/log/dmesg
  ports:
    - "9000"
  volumes:
    - ./app/site_php:/usr/share/nginx/html
    # Your php.ini
    - ./php5.6-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
  # environment:
    # Set your APP env variables here:
    # - APP_KEY=
    # - DB_HOST=
    # - DB_DATABASE=
    # - DB_USERNAME=
    # - DB_PASSWORD=
  links:
    - mysql:host_mysql

# database
mysql:
  image: mysql:latest
  ports:
    # Allow client to access 3306
    - "3306:3306"
  volumes:
    # NOTE: your data will be stored in ./mysql
    - ./mysql:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=your_mysql_password
